on:
  push:
    branches: main

  schedule:
    - cron: '0 22 * * 2'
    - cron: '0 22 * * 3'
    - cron: '0 22 * * 5'
    - cron: '0 11 * * 5'
    - cron: '0 22 * * 6'
    - cron: '0 22 * * 4'
    - cron: '0 22 * * 1'
    - cron: '0 22 * * 0'
    - cron: '0 6 * * 6'

project:
  type: website
  output-dir: docs

website:
  title: "betting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - EPL.qmd
      - nfl_values.qmd
      - nfl_player_props.qmd
      - nfl_player_props_values.qmd
      - nba_props.qmd
      - ottoneu.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px

editor: visual

