project:
  type: website
  output-dir: docs

website:
  title: "betting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - EPL.qmd
      - nfl_values.qmd
      - nfl_player_props.qmd
      - nfl_player_props_values.qmd
      - nba_player_props.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px

editor: visual

