on:
  workflow_dispatch:
  push:
    branches: main
  
  schedule:
    - cron: '0 22 * * 2'
    - cron: '0 22 * * 3'
    - cron: '0 22 * * 5'
    - cron: '0 11 * * 5'
    - cron: '0 22 * * 6'
    - cron: '0 22 * * 4'
    - cron: '0 22 * * 1'
    - cron: '0 22 * * 0'
    - cron: '0 6 * * 6'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages